### ISSUE TITLE
api-questions@khanacademy.org is bouncing

### ISSUE THREAD

**Issue by jfeldstein** [Khan/khan-api#102]
The email address listed in the wiki (https://github.com/Khan/khan-api/wiki/Khan-Academy-API-Recommended-Practices) is bouncing. 

To whom should we address direct api-related questions?

**Comment by CoryKhan** [comment]
Hello jfledstein,

We are working on reinstating this email address now.

Thanks for bringing this to our attention!

**Comment by CoryKhan** [comment]
Fixed!
