### ISSUE TITLE
oauth_callback redirect not working (javascript error with KA.staticUrl)

### ISSUE THREAD

**Issue by DaKaZ** [Khan/khan-api#104]
Hello,

We are working on wiring up our application with Khan Academy and I am not able to get a proper redirect back after authorizing the request token.  I always get the default callback along with the body "OK".

 I am getting a javascript error in the browser and I am wondering if this is the source of the problem.  Here is an example of our authorize call (after successfully getting the request token):

`https://www.khanacademy.org/api/auth2/authorize?oauth_callback=http%3A%2F%2Fdev.kudoso.com%2Fauth%2Fkhan_academy%2Fcallback&member_id=2&oauth_token=t0000003404618819`

The Javascript error I am getting is:

`/genfiles/javascript/en/shared-package-8caf31.js:94 Uncaught TypeError: KA.staticUrl is not a function`

I am getting this error in both Firefox and Chrome.  Any help would be appreciated.  Thanks!

**Comment by DaKaZ** [comment]
@csilvers - I see you replied to another open issue with the API, is there any chance you could look at the above and connect me to the right person at Khan to help sort this out?  This is a blocking issue for us and we'd really like to include the Khan integration with our release in July.

**Comment by csilvers** [comment]
I don't know very much about oauth at all, I'm afraid, but looking at our source code it seems like we're expecting an oauth_callback argument on /api/auth2/request_token, not /aip/auth2/authorize.  Try putting the parameter there instead and see if that fixes things for you.

**Comment by benjaminjkraft** [comment]
@thomaswp looked into a related issue a bit, so perhaps he can also chime in.  I believe the issue is indeed that we expect the callback on `/api/auth2/request_token`, as a GET parameter.  We then store that, and use it for future requests.

**Comment by thomaswp** [comment]
@DaKaZ, the callback is set when getting the request token, not when authorizing the request. See section 6.1.1 of [the spec](http://oauth.net/core/1.0a/#auth_step1). *However*, as @benjaminjkraft pointed out, unlike most OAuth1 endpoints, our system currently expects the callback to be provided as a URL parameter (the way you have it in you example), not as an authorization parameter, as is more common. We're hoping to support both in the future.

**Comment by DaKaZ** [comment]
@benjaminjkraft - thanks for that tip.  This is indeed a duplicate of issue #95 of the callback params not being respected in the headers.

As such, we have updated the Ruby gem to pass the callback in BOTH the headers and the params, as well as updated it to support the /auth2 path, the Gem is available for all here (under the auth2 brach):

https://github.com/DaKaZ/omniauth-khan-academy/tree/auth2 

Thanks!
