### ISSUE TITLE
API for getting User's articles

### ISSUE THREAD

**Issue by mark-ellul** [Khan/khan-api#106]
Hi,

Is there an API to get the user's articles?

The best I can find so far is the below link, however I don't know what to see the fkey to nor the version.

https://www.khanacademy.org/userprogressjs?version=18&id=http%3A%2F%2Fid.khanacademy.org%2F77b44decc75c421986477cc2e9a6837a&fkey=1.0_xwvltUIzdxmOKA%3D%3D_1464016507&v=2

Any help would be appreciated.

Regards

Mark

**Comment by benjaminjkraft** [comment]
I mentioned this over on StackOverflow, but cross-posting here for posterity:

I think `/api/v1/user/progress_summary` is your best bet.  I'm not sure why it's not listed on the API explorer, but here's the internal documentation:

```
    Return progress for a content type with started and completed lists.
    Takes a comma-separated `kind` param, like:
        /api/v1/user/progress_summary?kind=Video,Article
    and returns a dictionary that looks like:
        {"complete": ["a1314267931"], "started": []}
```

(You'll also need to pass a user identifier like `kaid`, similar to other `/api/v1/user` routes.)  Those IDs should match up with what you can get from the topic tree API, if you want more data on the individual content items.  As far as I can tell that's exactly the same data we use on the topic pages.
