### ISSUE TITLE
Khan CS: Child Account Can't See Their own spin-offs of programs

### ISSUE THREAD

**Issue by SharkFinPro** [Khan/khan-api#109]
Can You make it so that child accounts can see their spin-offs of other programs? (Right now they can't)

**Comment by benjaminjkraft** [comment]
Can you be more specific?  Is there a specific API call you're using that doesn't return the data you expect?

**Comment by SharkFinPro** [comment]
I don't know, i want child accounts to be their spin-offs of programs, they cant right now

**Comment by benjaminjkraft** [comment]
It sounds like what you're referring to is not a bug in the Khan Academy API.  For general support requests, see our [Help Center](https://khanacademy.zendesk.com/), where you can view our FAQ, Knowledge Base, and submit a support request.
