### ISSUE TITLE
topictree v2 broken

### ISSUE THREAD

**Issue by MaxDz** [Khan/khan-api#114]
The v2 API topictree call, which is the only one that returns article and video info (not in v1) is returning an error:
500: Error: Server Error / The server encountered an error and could not complete your request.

http://www.khanacademy.org/api/v2/topics/topictree

This began to happen at about the same time that the v1 topictree was being truncated, but is now fixed: [issue 111](https://github.com/Khan/khan-api/issues/111)

**Comment by csilvers** [comment]
It looks like the v2 API just uses too much memory now for our poor servers to handle.  We will have to figure out a way to improve that.  Folks are looking into it!, though I'm afraid I can't give a timeline.

btw, you can get video information via the v1 API call.  (That is the default if you don't specify `kind=`.)  But there's no way I can see to get the article information without using v2.

**Comment by MaxDz** [comment]
Tnx. Hopefully you can find a fix; it was slow, but was usable until about the end of June.

The video info is there, but not the titles; we use the v2 to get them for arts/vids in our translation control tool dAlEK [I am in the es translation team]. So that we can show the whole hierarchy by domain/subject/topic/tutorial, and then all the items inside (exs/art/vid/descr) that we are working on.

**Comment by MaxDz** [comment]
Still no fix?  We are stuck with the incomplete topictree from >1 month ago, and cannot update it :(  Could there be another way to get the v2 json???

**Comment by benjaminjkraft** [comment]
I'm really sorry about that -- we expected to be able to fix this properly sooner.  I think @wchargin is going to put in a temporary fix today.

**Comment by wchargin** [comment]
Hi @MaxDz—just pushed a fix that should let hopefully let it finish. (It does for me!) It may take longer than it used to, but should finish within a few minutes.

Sorry again for the inconvenience; holler if this still doesn't work!

**Comment by MaxDz** [comment]
Thanks everyone!!!  We seem to be back in business... no, it did not seem to take longer than before; but no matter, we update only every few days.
