### ISSUE TITLE
how to identify cheaters?

### ISSUE THREAD

**Issue by 58765786** [Khan/khan-api#118]
I am trying to figure out through the khan-api explorer how to programmatically identify if our middle school students are legitimately progressing through the math knowledge map or are only repeating the counting tens problem set over and over.   From my tests, khan gives 150 points every time they correctly do a 6 question problem set.  It doesn't matter if the student is repeating counting tens or doing 8th grade problems.   Some students have repeated counting tens over 100 times.

Is there a way to quickly quantify if a student is progressing and not trying to game the system?  Our students have 100,000+ khan points.  I can't use /api/v1/exercises because  I get a HTTP 500 error every time.

**Comment by benjaminjkraft** [comment]
What 500 error text are you getting, and can you post the exact URL you're hitting that returns a 500, and any other parameters you're passing?  This will help us investigate the problem.

**Comment by 58765786** [comment]
Ben,
I can query /api/v1/exercises now using postman.  I thought the api call was timing out, but it seems like the api explorer server was the issue.  You can close this.
