### ISSUE TITLE
Is it possible to list programming projects and information about them with the KA API?

### ISSUE THREAD

**Issue by douira** [Khan/khan-api#131]
For example, I'd like to be able to retrieve a list of projects I've created with the API, like it's displayed on this page: https://www.khanacademy.org/profile/douira/projects

**Comment by douira** [comment]
I solved it by looking at the requests the KA website makes when loading different sites. Would be nice if those endpoints were documented publicly, but it wasn't hard to find either. Thanks.

**Comment by csilvers** [comment]
There is no public API for this, as you discovered.  It looks like you found the internal API, but I just want to make sure you're aware that that API can change without notice, or even go away entirely.

We are rethinking our public API right now, and we'll keep your request in mind as we do so!

**Comment by douira** [comment]
Thank you for the info and the heads up!
