### ISSUE TITLE
api/v1/topictree math section bloat

### ISSUE THREAD

**Issue by kdadmin** [Khan/khan-api#135]
In 2012, there were 1618 unique videos in the math section.
Some of those videos were used in multiple math topics for 
a total of 1807 video references (189 duplicates).

It gave the appearance of a structured math class from
basic to advanced.

Today, including the kMAP section, there are 4605 unique
videos and 19,149 video references (14,544 duplicates). 

Basically the topictree repeats the math section 4X under
various math topic structures and labels.

I'm curious what the reason is for the duplication, and
if the api will ever get back to a sort of structured math 
class?

Thanks

**Comment by kdadmin** [comment]
Update/correction (cannot edit original post):

Bloat is probably the wrong way to describe it.

I can see the api supports custom curriculum for various 
organizations, i.e. ICSE, Illustrative Mathematics, Eureka
Math/EngageNY, etc.

My difficulty is sorting from the 80 child topics a single
KA curriculum which a student could work through from start 
to finish. Being a non-educator, I'm not qualified to do that.

Perhaps it's just a matter of topic organization?

**Comment by benjaminjkraft** [comment]
I don't think we have a supported way to do this right now other than looking at the list of topics shown on the website.  (The question of "topics a single student could work through" is a surprisingly complex one when you start to consider content aligned to different sets of standards.)  You can probably get reasonably close by looking only at topics that have "listed: true", but the best way may be to just look for the topics shown in the menu on khanacademy.org.
