### ISSUE TITLE
OAuthRequester showing Internal Sever Error 500

### ISSUE THREAD

**Issue by GovindCoding** [Khan/khan-api#140]
When I login and accept user login and try to access khan API "OAuthRequester" using consumerKey, oauthToken and accessTokenParams it showing me a "500 Internal Server Error".

**Comment by 23harolds** [comment]
Hi,

We are also experiencing same issue.

Hope this will be resolved soon.

Thanks & Regards.

**Comment by GovindCoding** [comment]
Hi,

Thanks for the update. I am able to resolve, after spending 2 days. It was because of OAuthRequester module calling curl_init() function and in my PHP curl_init() function is undefined. So, I have installed curl using this command "sudo apt-get install php7.1-curl" as I am having PHP 7.1, you can use installed PHP version.

**Comment by 23harolds** [comment]
Wow thanks, I'll try it. We have also had a recent update of php version.

**Comment by 23harolds** [comment]
I am experiencing a different problem. I get an error from
Oauthrequester,php file:

Undefined variable: code oauth-php/library/OAuthRequester.php on line 485
PHP Fatal error:  Uncaught exception 'OAuthException2' with message
'Unexpected result from the server "
https://www.khanacademy.org/api/auth/access_token" () while requesting an
access token' oauth-php/library/OAuthRequester.php:258
Stack trace:
#0 /Controller.php(794):
OAuthRequester::requestAccessToken('gCjGBfnQBAG8u4R...',
't47338259573309...', 0, 'POST', Array)
#1 /Controller.php(48): Controller->doOathAuthentication()
#2 /home.php(5): Controller->invoke()
#3 require_once('/home/sville/pu...')
#4 /index.php(29): require_once('/home/sville/pu...')
#5 {main}
  thrown in controller/oauth-php/library/OAuthRequester.php on line 258

Hope you can help me. Thanks a lot in advance.

**Comment by jb-1980** [comment]
Hi @23harolds, it sounds like you are having the exact issue as #141. I am wondering if it is getting a similar response that I am seeing in Python, essentially `OAuth error. Invalid signature.`, which indicates that the library is not producing the correct signature string that the Khan Academy API is expecting.

Anyways, you probably want to add your issue to #141 instead of tracking it here on a closed thread.
