### ISSUE TITLE
Api explorer link is not working

### ISSUE THREAD

**Issue by owaisibrahim099** [Khan/khan-api#150]
![api documentation error](https://user-images.githubusercontent.com/58456329/73197330-ec8cde00-4152-11ea-90c9-13f8f525c8a4.PNG)

**Comment by seandriedger** [comment]
Hello,
Thanks for your concern, but we have deliberately shut down the API Explorer (and removed the link from https://github.com/Khan/khan-api), as part of the deprecation of the Public API. You can find more details about the deprecation plan and timeline here: https://github.com/Khan/khan-api.
  Sean
