### ISSUE TITLE
Disappointed :(

### ISSUE THREAD

**Issue by rexwal** [Khan/khan-api#151]
Sad that there has been no reply to this community :( 

/exercises stopped returning new data so it is pretty much dead already..

**Comment by seandriedger** [comment]
Hi @rexwal - I'm afraid that the response that I provided in an earlier thread still represents our current plans for the Public API: https://github.com/Khan/khan-api/issues/149#issuecomment-564263460.

However, we're not *expecting* any degradation of functionality for the /api/v1/exercises/* endpoints until we remove them on July 1st 2020. So if you're seeing a problem with them, I'd suggest submitting a help desk ticket here: https://khanacademy.zendesk.com/hc/en-us.
