### ISSUE TITLE
The version link in wiki/Khan-Academy-API is broken.

### ISSUE THREAD

**Issue by drakezhard** [Khan/khan-api#82]
https://sites.google.com/a/khanacademy.org/forge/for-developers/technical/api

Page not found

We're sorry, but we were unable to locate the page you requested.

Here are some similar pages from this site:

    rest-apis
    testing-the-api-w-oauth
    all-about-rendering-web-pages 

Also is there was a version 2 of the api, and what credentials do I need to program against it?

**Comment by alangpierce** [comment]
Thanks, that was referencing a really old version, and I guess we got rid of the documentation a while ago. I just removed the link and rephrased it.

There has been some work on improvements to the API (which we've internally called "API v2"), but most of those have been focused on improvements to our internal APIs used by the KA website and mobile app. I'm hoping that we can eventually release a v2 of our public API, but it probably won't happen any time soon.
