### ISSUE TITLE
Are there any guidelines for maximum api calls?

### ISSUE THREAD

**Issue by drakezhard** [Khan/khan-api#84]
If I do an api call every minute will the server complain? I'm not dealing with a big query just the result of /api/v1/students for 60 students.

**Comment by alangpierce** [comment]
Sorry for taking so long to get to this.

One call every 60 seconds should be totally fine. We haven't previously documented any guidelines or restrictions on the max rate of API calls you can make, but I think one API call per second seems like a reasonable maximum. But it also should be fine to make multiple API calls in the same second if it's a short burst.
