### ISSUE TITLE
api/v1/topictree:  "kind": "Topic" - "content_kind": "Topic"

### ISSUE THREAD

**Issue by kdadmin** [Khan/khan-api#87]
We used to have the string:value pairs:
 "kind": "Topic"
 "kind": "Video"
along with string:value pairs:
 "content_kind": "Topic"
 "content_kind": "Video"
but now only have:
 "content_kind": "Topic"
 "content_kind": "Video"
for topic and video objects that have more then just an id;

This fouls my parser as it is coded to use only the
 "kind": "Topic"
 "kind": "Video"
pairs.

If this is a permenent API change, I will need to rework my app.
Please let me know.
Thanks,
Gary

**Comment by spicyj** [comment]
cc @chrisklaiber

**Comment by alangpierce** [comment]
Sorry about that, we got rid of some of the unimportant and redundant fields on topictree since the response size was getting too large. But I can add `kind` back to un-break your code.

**Comment by alangpierce** [comment]
Ok, I think this should be fixed now.

**Comment by kdadmin** [comment]
That fixed it. Thanks.
