### ISSUE TITLE
User badges problem

### ISSUE THREAD

**Issue by dani3lviana** [Khan/khan-api#89]
I'm trying get the user badges, but the API isn't returning the node user_badges.

```php
$this->store->addServerToken(self::CONSUMER_KEY, 'request', self::OAUTH_TOKEN, self::OAUTH_TOKEN_SECRET, 0);

OAuthRequester::requestAccessToken(self::CONSUMER_KEY, self::OAUTH_TOKEN, 0, 'POST', array('oauth_verifier' => self::OAUTH_VERIFIER));

$request = new OAuthRequester(self::URL . "/api/v1/badges", 'GET', array('email' => $email));
$result = $request->doRequest(0);
```

This is returning all the badges

**Comment by alangpierce** [comment]
Hi, thanks for reporting. This was indeed a bug that was introduced a few months ago, where the `user_badges` field would never show up on the response. I just deployed a change that should fix the issue.
