### ISSUE TITLE
Examples for REST API

### ISSUE THREAD

**Issue by mobilemeans** [Khan/khan-api#90]
How can I find the list of topics that are related to the top level categories available in http://www.khanacademy.org/api/v1/topic/?  Your examples refer to banking-and-money as one example but when I try to navigate through the JSON response my browser crashes and I can not find any relationships.  My goal is to obtain the list of top level categories and then the list of videos associated to each.

**Comment by alangpierce** [comment]
We have a (mostly) four-level content hierarchy, where any node in that tree (except actual content items like videos and exercises) is considered a "topic" that can be loaded using /api/v1/topic .

If you're looking to find the content manually, you can find the slug (i.e. the identifier) for a topic by visiting it in the website and looking at the URL. For example, by looking at this URL for a video on the website:

https://www.khanacademy.org/science/organic-chemistry/organic-structures/formal-charge-resonance/v/resonance-intro-jay

you can find that "science", "organic-chemistry", "organic-structures", and "formal-charge-resonance" are all topics that you can load with URLs like [/api/v1/topic/organic-structures](http://www.khanacademy.org/api/v1/topic/organic-structures) .

The top-level "root of all knowledge" topic has the slug "root", so you can load it with [/api/v1/topic/root](http://www.khanacademy.org/api/v1/topic/root). The JSON response has the slugs of all of the children, so you could use that to navigate down the topic hierarchy.

Or, if you want to just load every topic, you can load [/api/v1/topictree](khanacademy.org/api/v1/topictree), which returns a giant JSON response that's about 30MB. Loading it in the browser works for me, but it's definitely a bit big and it may be best to download it separately and work with it as a file.
