### ISSUE TITLE
Invalid Signature OAuth Error in test_client2

### ISSUE THREAD

**Issue by beaconofknope** [Khan/khan-api#92]
There is a problem with the example test.py in the test_client2 folder. Any API call that requires actual authentication does not return any data due to no signature being added during the session creation. This problem is not seen in the test.py in the test_client folder. I may be missing something?

The call I am making is /api/v1/user?email=XXXX@XXX.com

**Comment by alangpierce** [comment]
Thanks for reporting, this should be fixed by https://github.com/Khan/khan-api/pull/93 .
